config/routes.rb
Rails.application.routes.draw do
  resources :responses, only: [:new, :create, :index]
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/response.rb
class Response < ApplicationRecord
  validates :name, presence: true
  validates :attending, presence: true

  def display_attendance
  	case attending
  	when 1
  		"Day One Only"
		when 2
  		"Both Days"
		when 3
  		"Neither"
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
    @response = Response.new
  end

  def create
    @response = Response.new(response_params)
    if @response.save
      redirect_to new_response_path(message: "Thankyou for RSVP'ing!")
    else
      render :new
    end
  end

  def index
    if params[:sort]
      @responses = Response.order("#{params[:sort]} asc")
    else
      @responses = Response.order("name asc")
    end
    @day_one = @responses.where(attending: 1)
    @both = @responses.where(attending: 2)
    @neither = @responses.where(attending: 3)
    @saturday_accommodation = @responses.where(accommodation: 'Saturday Night').or(@responses.where(accommodation: 'Both'))
    @sunday_accommodation = @responses.where(accommodation: 'Sunday Night').or(@responses.where(accommodation: 'Both'))
  end

  private

  def response_params
    params.require(:response).permit(:name, :diet, :accommodation, :attending)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laura & Sean Wedding</title>
    <meta name="description" content="Together with their families Laura & Sean joyfully invite you to their wedding celebration">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;700&family=Open+Sans:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="sean-navbar shared-navbar">
  <div class="navbar-inner">
    <div class="navbar-link">
      <a class="navbar-link-text" href="#details">
        THE DETAILS
      </a>
    </div>
    <div class="navbar-link">
      <a class="navbar-link-text" href="#directions">
        GETTING THERE
      </a>
    </div>
    <a class="navbar-link-text large-navbar-link" href="#top">
      Laura & Sean
    </a>
    <div class="navbar-link">
      <a class="navbar-link-text" href="#accomodation">
        ACCOMODATION
      </a>
    </div>
    <div class="navbar-link">
      <%= link_to "RSVP", new_response_path, class: "navbar-link-text" %>
    </div>
  </div>
</div>
<div id="top"></div>
<div class="parallax" data-controller="menu">
  <div class="hamburger-holder">
    <%= image_tag "favicon.ico", alt: "alttext" %>
    <div class="hamburger hamburger--spring" data-action="click->menu#toggleNavbar">
      <div class="hamburger-box">
        <div class="hamburger-inner"></div>
      </div>
    </div>
  </div>
  <div id="dropdown" data-target="menu.dropdown">
    <%= link_to "THE DETAILS", root_path, class: "dropdown-option navbar-link-text" %>
    <div class="divider"></div>
    <%= link_to "GETTING THERE", root_path, class: "dropdown-option navbar-link-text" %>
    <div class="divider"></div>
    <%= link_to "ACCOMODATION", root_path, class: "dropdown-option navbar-link-text" %>
    <div class="divider"></div>
    <%= link_to "RSVP", new_response_path, class: "dropdown-option navbar-link-text" %>
  </div>
</div>
<div class="landing-section">
  <p class="gold">Together with their families</p>
  <h1 class="gold garamond xl-text">Laura & Sean</h1>
  <p class="gold text-center">joyfully invite you to their <br> wedding celebration</p>
  <div class="vertical-line"></div>
  <h2 class="gold garamond large-text">April 9, 2022</h2>
  <p class="gold">At Virginia Park Lodge</p>
  <a class="gold-button" href="#details">More details</a>
</div>
<div class="home-section" id="details">
  <%= image_tag "eucalyptus3.png", alt: "Eucalyptus leaves", class: "eucalyptus leaves-top-right" %>
  <%= image_tag "eucalyptus.png", alt: "Eucalyptus leaves", class: "eucalyptus leaves-bottom-left" %>
  <h2 class="large-text garamond gold text-center pt-5 pb-3">Day One</h2>
  <div class="details">
    <%= render "shared/details" %>
  </div>
  <h2 class="large-text garamond gold text-center pt-5 pb-3">Day Two</h2>
  <div class="day-two-container">
    <div class="day-two-flex">
      <div class="day-two-details pt-5">
        <p class="gold pb-4">We would love for you to join us for more celebrations.</p>
        <p class="gold pb-4">There are beautiful walks around the lake and also the opportunity to play a short round of golf on the attached course.</p>
        <p class="gold pb-4">A BBQ will be held on the front lawn of Virginia Park Lodge from 3.00pm followed by music and garden games until late.</p>
      </div>
      <img src="https://www.virginiaparklodge.com/wp-content/uploads/2019/02/AUTUMN-83-Medium.jpg" alt="" class="day-two-img">
    </div>
  </div>
  <%= link_to "RSVP", new_response_path, class: "gold-button mx-auto my-5"  %>
</div>
<div class="home-directions" id="directions">
  <h2 class="large-text garamond white text-center pt-5">Getting There</h2>
  <div class="vertical-line white-line mx-auto my-5"></div>
  <div id="map"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
       ></div>
  <div class="d-flex justify-content-between mx-auto mt-5 detail-holder">
    <div class="detail-para">
      <p class="white bold">Ceremony</p>
      <a class="direction-link" target="_blank" href="https://www.google.com/maps/place/Church+of+the+Immaculate+Conception,+Kingscourt/@53.905768,-6.8156468,14.08z/data=!4m5!3m4!1s0x4860acd9f2736acd:0x71e5a20eb90bf8d9!8m2!3d53.9040221!4d-6.8078099">The Church of the Immaculate Conception, Kingscourt, Co. Cavan. A82 E650</a>
      <p class="white">From Dublin Airport the journey can take an hour.  However please allocate 90 minutes if coming from Dublin City Centre</p>
    </div>
    <div class="detail-para">
      <p class="white bold">Wedding Reception</p>
      <a class="direction-link" target="_blank" href="https://www.google.com/maps/place/Virginia+Park+Lodge/@53.8361402,-7.0983423,15.71z/data=!4m8!3m7!1s0x485dfdd25b84110d:0xe58a8afcab37d79e!5m2!4m1!1i2!8m2!3d53.8356524!4d-7.0945159">Virginia Park Lodge, Virginia, Co. Cavan, A82 T2N6</a>
      <p class="white">From the ceremony this is a 30 minute journey</p>
    </div>
  </div>
</div>
<div class="home-section" id="accomodation">
  <h2 class="large-text garamond gold text-center pt-5">Accomodation</h2>
  <div class="vertical-line mx-auto my-5"></div>
  <div class="container">
    <p class="gold bold">On Site</p>
    <p class="gold">We anticipate a late finish and advise all guests to stay on site where possible. There is ample on site accommodation at Virginia Park Lodge for both the Saturday and Sunday. </p>
    <p class="gold">There are a selection of rooms within the Lodge and the cottages. We will be allocating accommodation as required.</p>
    <p class="gold">Please indicate on the website RSVP if you require accommodation.</p>
    <p class="gold">Unfortunately there is no accommodation available on site the Friday night due to another wedding. You do not need to contact Virginia Park Lodge to arrange accommodation for the Saturday and Sunday: once we have confirmation of numbers we will be in contact with you directly to organise rooms</p>
    <p class="gold bold">Alternative accommodation</p>
    <p class="gold">We recommend that guests stay locally in Virginia Co.Cavan or Kells in Co.Meath.</p>
  </div>
</div>
<div class="home-faqs" id="faqs">
  <h2 class="large-text garamond white text-center pt-5">FAQs</h2>
  <div class="container">
    <p class="white bold mt-4">Children</p>
    <p class="white">Unfortunately, due to number restrictions, we have been unable to extend our invitations to include any children. Only children involved in the wedding party will be present. We hope that parents can make arrangements so they can join us on our special day.</p>
    <p class="white bold mt-4">Gifts</p>
    <p class="white">We have registered <a class="white-link" href="http://www.weddingshop.com/Buy/View/100497">a list with the Wedding Shop</a> for inspiration. Please do not feel obliged to use this website.</p>
    <p class="white bold mt-4">Dress Code</p>
    <p class="white">Lounge Suits and Cocktail dresses.</p>
    <p class="white bold mt-4">The Night Before</p>
    <p class="white">We are aware many of our guests will be travelling from the UK. We will be having some drinks locally and will advise nearer the time.</p>
    <p class="white bold mt-4">Covid-19</p>
    <p class="white">We will be monitoring the situation closely and will advise via email closer to the time.</p>
    <p class="white bold mt-4">Contact Details</p>
    <p class="white">Please don't hesitate to reach out if you have any questions.</p>
    <p class="white">Laura: <a class="white-link" href="tel:+447875970725">+447875970725</a></p>
    <p class="white">Sean: <a class="white-link" href="tel:+447984143498">+447984143498</a></p>
    <p class="white">Email: <a class="white-link" href="mailto:lauraandsean2022@gmail.com">lauraandsean2022@gmail.com</a></p>
  </div>
</div>
<div class="home-footer">
  <a href="#top" class="link">
    <div class="d-flex flex-column align-items-center justify-content-center">
      <%= image_tag "arrow-up.png", alt: "alttext", class: "up-arrow" %>
      <p class="m-0 link-text">Back To Top</p>
    </div>
  </a>
  <span class="footer-attribution">Made with love by <a href="https://www.hoxton-digital.com/services" target="_blank">Hoxton Digital</a></span>
</div>

<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
  AOS.init();
</script>

<script>
  window.addEventListener('turbolinks:load', (event) => {
    const navbar = document.querySelector('.sean-navbar')
    if (navbar) {
      window.addEventListener('scroll', (event) => {
        if (window.scrollY >= 5) {
          navbar.classList.add('inverted-navbar');
        } else {
          navbar.classList.remove('inverted-navbar');
        }
      })
      const markers = document.querySelectorAll('.mapboxgl-marker');
      markers.forEach((marker) => {
        marker.firstElementChild.firstElementChild.children[1].style.fill = "#AF925D"
      })
    }
  });

  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
      e.preventDefault();

      document.querySelector(this.getAttribute('href')).scrollIntoView({
          behavior: 'smooth'
      });
    });
  });
</script>

app/views/responses/index.html.erb
<div class="container">
  <% if params[:password] %>
    <% if params[:password][:name] == "mybrotheristhebest" %>
      <div class="analytics-highlights">
        <div class="analytics-highlight">
          <h5>Day One <br>Attendees</h5>
          <p><%= @day_one.length %></p>
        </div>
        <div class="analytics-highlight">
          <h5>Both Day <br>Attendees</h5>
          <p><%= @both.length %></p>
        </div>
        <div class="analytics-highlight">
          <h5>Unable To <br>Attend</h5>
          <p><%= @neither.length %></p>
        </div>
        <div class="analytics-highlight">
          <h5>Need Saturday <br>Accommodation</h5>
          <p><%= @saturday_accommodation.length %></p>
        </div>
        <div class="analytics-highlight">
          <h5>Need Sunday <br>Accommodation</h5>
          <p><%= @sunday_accommodation.length %></p>
        </div>
      </div>
      <p class="gold">Sort table by clicking a header</p>
      <table class="response-table">
        <tr class="response-row response-header">
          <th><%= link_to "Name", sort: "name", password: { name: 'mybrotheristhebest'} %></th>
          <th><%= link_to "Attendance", sort: "attending", password: { name: 'mybrotheristhebest'} %></th>
          <th><%= link_to "Dietary Requirements", sort: "diet", password: { name: 'mybrotheristhebest'} %></th>
          <th><%= link_to "Accommodation", sort: "accommodation", password: { name: 'mybrotheristhebest'} %></th>
        </tr>
        <% @responses.each_with_index do |response, index| %>
          <tr class="<%= index.odd? ? 'response-row odd-row' : 'response-row' %>">
            <td><%= response.name %></td>
            <td><%= response.display_attendance %></td>
            <td><%= response.diet.blank? ? 'None' : response.diet %></td>
            <td><%= response.accommodation %></td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <div class="password-holder">
        <%= simple_form_for :password, url: responses_path, method: :get do |f| %>
          <%= f.input :name, label: false %>
          <%= f.submit "Submit Password", class: "gold-button w-100" %>
        <% end  %>
      </div>
    <% end %> 
  <% else %>
    <div class="password-holder">
      <%= simple_form_for :password, url: responses_path, method: :get do |f| %>
        <%= f.input :name, label: false %>
        <%= f.submit "Submit Password", class: "gold-button w-100" %>
      <% end  %>
    </div>
  <% end %>
</div>

app/views/responses/new.html.erb
<div class="inverted-navbar shared-navbar">
  <div class="navbar-inner">
    <div class="navbar-link">
      <%= link_to "THE DETAILS", root_path(anchor: "details"), class: "navbar-link-text" %>
    </div>
    <div class="navbar-link">
      <%= link_to "GETTING THERE", root_path(anchor: "directions"), class: "navbar-link-text" %>
    </div>
    <%= link_to "Laura & Sean", root_path, class: "navbar-link-text large-navbar-link" %>
    <div class="navbar-link">
      <%= link_to "ACCOMODATION", root_path(anchor: "accomodation"), class: "navbar-link-text" %>
    </div>
    <div class="navbar-link">
      <%= link_to "RSVP", new_response_path, class: "navbar-link-text" %>
    </div>
  </div>
</div>
<div id="top"></div>
<div class="" data-controller="menu">
  <div class="hamburger-holder">
    <%= image_tag "favicon.ico", alt: "alttext" %>
    <div class="hamburger hamburger--spring" data-action="click->menu#toggleNavbar">
      <div class="hamburger-box">
        <div class="hamburger-inner"></div>
      </div>
    </div>
  </div>
  <div id="dropdown" data-target="menu.dropdown">
    <%= link_to "THE DETAILS", root_path, class: "dropdown-option navbar-link-text" %>
    <div class="divider"></div>
    <%= link_to "GETTING THERE", root_path, class: "dropdown-option navbar-link-text" %>
    <div class="divider"></div>
    <%= link_to "ACCOMODATION", root_path, class: "dropdown-option navbar-link-text" %>
    <div class="divider"></div>
    <%= link_to "RSVP", new_response_path, class: "dropdown-option navbar-link-text" %>
  </div>
</div>
<div class="rsvp-container" data-controller="rsvp">
  <%= image_tag "eucalyptus3.png", alt: "Eucalyptus leaves", class: "eucalyptus leaves-top-right rsvp-plant rsvp-plant-1" %>
  <%= image_tag "eucalyptus.png", alt: "Eucalyptus leaves", class: "eucalyptus leaves-bottom-left rsvp-plant" %>
  <% if params[:message] %>
    <h2 class="medium-text garamond gold pt-5 pb-3"><%= params[:message] %></h2>
    <%= link_to "Add another atendee", new_response_path, class: "gold-button", style: "width: 250px" %>
  <% else %>
    <div class="rsvp-form">
      <h2 class="medium-text garamond gold pt-5 pb-3">Kindly respond by 4th of February</h2>
      <%= simple_form_for(@response) do |f| %>
        <%= f.label :name, "Name(s)", class: "rsvp-label m-0" %>
        <%= f.input :name, label: false, input_html: { class: "rsvp-input" } %>
        <fieldset class="form-group check_boxes optional response_attendances">
          <legend class="col-form-label pt-0">Will be attending:</legend>
          <input type="hidden" name="attending" value="">
          <div class="form-check">
            <input class="form-check-input check_boxes optional" type="checkbox" value="1" id="attending_1" data-action="click->rsvp#toggleAttendance" data-target="rsvp.checkbox">
            <label class="form-check-label collection_check_boxes" for="attending_1">Day One Only</label>
          </div>
          <div class="form-check">
            <input class="form-check-input check_boxes optional" type="checkbox" value="2" id="attending_2" data-action="click->rsvp#toggleAttendance" data-target="rsvp.checkbox">
            <label class="form-check-label collection_check_boxes" for="attending_2">Both Days</label>
          </div>
          <div class="form-check">
            <input class="form-check-input check_boxes optional" type="checkbox" value="3" id="attending_3" data-action="click->rsvp#toggleAttendance" data-target="rsvp.checkbox">
            <label class="form-check-label collection_check_boxes" for="attending_3">Neither</label>
          </div>
        </fieldset>
        <%= f.input :attending, label: false, input_html: { class: "d-none", data: { target: "rsvp.attendingInput" } } %>
        <%= f.label :diet, "Special dietary requirements", class: "rsvp-label m-0 mt-3" %>
        <%= f.input :diet, label: false, placeholder: "Vegan, vegetarian, coeliac, etc", input_html: { class: "rsvp-input" } %>
        <%= f.label :accommodation, "Accommodation", class: "rsvp-label ml-0 mt-3" %>
        <%= f.input :accommodation, label: false, collection: ["Saturday Night", "Sunday Night", "Both"], prompt: 'Not needed' %>
        <%= f.submit "RSVP", class: "gold-button mx-auto my-5" %>
      <% end %>
    </div>
  <% end %>
</div>

<script>
  window.addEventListener('turbolinks:load', (event) => {
    const burger = document.querySelector('.burger-menu')
    const dropdown = document.getElementById('dropdown')
    const closeBtn = document.getElementById('close-btn')
    if (burger) {
      burger.addEventListener('click', (event) => {
        dropdown.classList.toggle('d-none')
      })
      closeBtn.addEventListener('click', (event) => {
        dropdown.classList.toggle('d-none')
      })
    }
  });
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert" data-controller="rsvp">
    <%= notice %>
    <button data-action="click->rsvp#closeFlash" type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert" data-controller="rsvp">
    <%= alert %>
    <button data-action="click->rsvp#closeFlash" type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="sean-navbar shared-navbar">
  <div class="navbar-inner">
    <div class="navbar-link">
      <a class="navbar-link-text" href="#details">
        THE DETAILS
      </a>
    </div>
    <div class="navbar-link">
      <a class="navbar-link-text" href="#directions">
        GETTING THERE
      </a>
    </div>
    <a class="navbar-link-text large-navbar-link" href="#top">
      Laura & Sean
    </a>
    <div class="navbar-link">
      <a class="navbar-link-text" href="#accomodation">
        ACCOMODATION
      </a>
    </div>
    <div class="navbar-link">
      <%= link_to "RSVP", new_response_path, class: "navbar-link-text" %>
    </div>
  </div>
</div>
<div id="top"></div>
<div class="parallax" data-controller="menu">
  <div class="hamburger hamburger--spring" data-action="click->menu#toggleNavbar">
    <div class="hamburger-box">
      <div class="hamburger-inner"></div>
    </div>
  </div>
  <div id="dropdown" data-target="menu.dropdown">
    <%= link_to "THE DETAILS", root_path, class: "dropdown-option navbar-link-text" %>
    <div class="divider"></div>
    <%= link_to "GETTING THERE", root_path, class: "dropdown-option navbar-link-text" %>
    <div class="divider"></div>
    <%= link_to "ACCOMODATION", root_path, class: "dropdown-option navbar-link-text" %>
    <div class="divider"></div>
    <%= link_to "RSVP", new_response_path, class: "dropdown-option navbar-link-text" %>
  </div>
</div>